# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uDOxVDgePD3yCpVjEYUpwqSgvemyZOVk
"""

#тип данных
a = 4
b = 3.02345
stroka = 'qwerty'
st_b = str (b)
l = list('asfasf' )
ls_1 = [2, 5, 4, a, b, stroka]
t = tuple ('1, 2, 3')
t_1 = (1, 3)
mn = set ('1, 2, 3')
mn_1 = {1, 2, 3}
d = {
    a:l,
    b: stroka,
     'c':mn
     }
print (l, ls_1)